# Generated by Django 4.2.1 on 2023-05-23 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sedex', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=500, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaDevolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=100)),
                ('devolucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_control.devolucao')),
            ],
        ),
    ]
