# Generated by Django 4.2.1 on 2023-06-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='codigo_sedex',
            field=models.CharField(error_messages={'unique': 'Este código já existe'}, max_length=20, unique=True),
        ),
    ]
