# Generated by Django 4.2.1 on 2023-06-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0002_alter_devolucao_codigo_sedex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='email',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
