# Generated by Django 4.2.1 on 2023-06-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_alter_devolucao_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucao',
            name='codigo_postagem',
            field=models.CharField(error_messages={'unique': 'Este código já existe'}, max_length=20, null=True, unique=True),
        ),
    ]
