# Generated by Django 4.2.1 on 2023-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0005_alter_devolucao_codigo_sedex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='codigo_postagem',
            field=models.CharField(error_messages={'unique': 'Este código já existe'}, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devolucao',
            name='codigo_sedex',
            field=models.CharField(error_messages={'unique': 'Este código já existe'}, max_length=500),
        ),
    ]
