# Generated by Django 4.2.1 on 2023-06-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0006_alter_devolucao_codigo_postagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='data',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
