# Generated by Django 4.2.1 on 2023-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0007_alter_devolucao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucao',
            name='data',
            field=models.DateTimeField(null=True),
        ),
    ]
